<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-9538315" failures="1" tests="2" name="Test2" time="0.154" errors="0" timestamp="2023-08-11T20:19:38 IST">
  <testcase classname="testNGlistener.Listner" name="testtofail" time="0.046">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testNGlistener.Listner.testtofail(Listner.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testtofail -->
  <testcase classname="testNGlistener.Listner" name="testtopass" time="0.013"/>
</testsuite> <!-- Test2 -->
